[package]
name = "whatsapp_scrapper"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
env_logger = "0.11.3"
log = "0.4.21"
regex = "1.10.5"
sequelite = { version = "0.2.3", features = ["bundled"] }
serde = { version = "1.0.203", features = ["derive"] }
